### ISSUE TITLE
Failed is always 0

### ISSUE THREAD

**Issue by tostasqb** [ajitsing/sidekiq_queue_metrics#2]
No Failed processes are being counted (always 0). Using
- rails 5.2.2
- sidekiq 5.2.7
- sidekiq_queue_metrics 2.0

**Comment by ajitsing** [comment]
Hi @tostasqb, Thanks for reporting the issue. I just wanted to know more details around it.

1. Which metric shows the failed count as zero, the page which contains all the queues metrics or an individual queue summary page?
2. Are other counters (e.g processed, enqueued, etc.) working fine?

Can you also check that the sidekiq logs are not giving any error? Especially check for logs like ```Error calling death handler```

**Comment by tostasqb** [comment]
Hi @ajitsing. 
(See imgur image below)
All failed queues are zeroed.
Maybe an issue because of sidekiq retries? Processed queue is fine. Not really sure if all other queues are working ok since workers are quite fast.
Can't see any calls to `Error calling death handler` on sidekiq logs.

![sidekiq][image]

[image]: https://i.imgur.com/0N5f09Y.jpg

**Comment by ajitsing** [comment]
I tried reproducing this issue on my local machine with sidekiq 5.2.7. I can see the failed count as expected.
Can you please try to intentionally fail a job for a particular queue and see if it works? Maybe by raising an exception in ```perform``` method. I believe it should work.

Also in the above image, I can see only 4 jobs in dead state, maybe none of the jobs got failed after you added ```sidekiq_queue_metrics``` plugin.

**Comment by ajitsing** [comment]
Hi @tostasqb, any update of this? Are you still facing the issue?

**Comment by tostasqb** [comment]
Hi @ajitsing 

It is. I created a worker with this sample code

```
class ContactWorker
  include Sidekiq::Worker
  sidekiq_options queue: 'contact'

  def perform
    raise 'stuff'
  end
end

```

After calling the first time with `ContactWorker.perform_async` it failed and the job got queued on the "In Retry" queue but the failed counter got stuck in 0. The general Failed counter did go up 1 number.

![sidekiq][image]

[image]: https://i.imgur.com/HYNNTnS.jpg

**Comment by ajitsing** [comment]
The failed count increases only after all the retries are exhausted.

**Comment by tostasqb** [comment]
Ok I see. 
Would you be open to re-evaluate that? being that this is a counter for each queue and sidekiq does count failed processes as many as retries are made, I think it makes sense that it behaves just the same. So when all counters start from zero, the sum of all individual failed queues would be equal to the general failed count. This makes sense across the board, for all queue status.

**Comment by ajitsing** [comment]
Actually, the idea was that the failed counter should contain the number of actual failures, not the once which got processed with a retry. But if you feel that we should count all the failures irrespective of they got processed in retry or not then maybe we can introduce a config for that. What are your thoughts?
