### ISSUE TITLE
sidekiq versions compatibility

### ISSUE THREAD

**Issue by ivanetchart** [ajitsing/sidekiq_queue_metrics#4]
It may not be a bug itself, but looks like this gem is compatible only with Sidekiq >= 5.1. It seems that during `Sidekiq::QueueMetrics.init` it attaches a monitor to sidekiq `death_handlers` which is a >= 5.1 feature. Gemspec specifices that it supports `sidekiq >= 3.0`. Not sure if this is expected, and a backward compatibility is wanted (which I think should be great to support rails 3.2 and older versions) or a just a `gemspec` update.

Thanks!

**Comment by ajitsing** [comment]
Hi @ivanetchart,

You are right that death handlers are only supported from sidekiq 5.1 onwards. I will make the change and publish the gem.

**Comment by ivanetchart** [comment]
hey @ajitsing, I will be likely working on a PR to (try) add support for older sidekiq versions (we need it for a company project). I'm exploring adding a `sidekiq_retries_exhausted` hook dynamicall during `Sidekiq::QueueMetrics.init`.  If you want, you can hold off the release, I can send a PR tomorrow, and we can discuss the approach. What do you think ?

**Comment by ajitsing** [comment]
Sure let's talk about it. But for now, I have already published the gem with the fix.

**Comment by ivanetchart** [comment]
@ajitsing just sent a PR for this issue. Let me know your thoughts!

Thanks

**Comment by ajitsing** [comment]
Addressed in [Release 3.0.0](https://github.com/ajitsing/sidekiq_queue_metrics/releases/tag/3.0.0)
